name: Rust CI

on:
  push:
    branches:
      - main  
      - dev  
  pull_request:
    branches:
      - main 
      - dev  

jobs:
  checking-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Caching Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check Formatting
        run: cargo fmt --check

      - name: Run Clippy (Linting)
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test --verbose


      - name: Run cargo-audit
        uses: actions-rust-lang/audit@v1
 
