name: Rust CI

on:
  push:
    branches:
      - main  
      - dev  
  pull_request:
    branches:
      - main 
      - dev  

jobs:
  checking-repo:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out repository code

      - name: Caching Dependencies
        uses: actions/cache@v4  # Caches dependencies for faster builds
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Rust
        uses: rust-lang/setup-rust-action@v1
        with:
          rust-version: stable
          components: clippy, rustfmt  # Installs Clippy and Rustfmt

      - name: Install cargo-audit
        run: cargo install cargo-audit  # Ensures cargo-audit is available

      - name: Check Formatting
        run: cargo fmt -- --check  # Fails if the code is not formatted

      - name: Run Clippy (Linting)
        run: cargo clippy -- -D warnings  # Treats warnings as errors

      - name: Run Tests
        run: cargo test --verbose  # Runs tests with verbose output

      - name: Run Security Audit
        run: cargo audit  # Checks for security vulnerabilities
