on:
    push: 
      branches:
        - main
        - dev
  
jobs:
    docker-build:
     # Fixed job dependency
      runs-on: ubuntu-latest
      permissions:
        packages: write  # Grant permission to write to GHCR
    
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
    
        - name: Log in to GitHub Container Registry (GHCR)
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ GITHUB_REPOSITORY_OWNER }}  # Use the TOKEN secret for the username
            password: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN secret for the password
    
        - name: Build and push Docker image
          uses: docker/build-push-action@v3
          with:
            context: .
            push: true
            platforms: linux/amd64,linux/arm64
            tags: |
              ghcr.io/${{ secrets.TOKEN }}/sync_https_server:sha-${{ github.sha }}
              ghcr.io/${{ secrets.TOKEN }}/sync_https_server:branch-${{ github.ref_name }}
              ghcr.io/${{ secrets.TOKEN }}/sync_https_server:latest
    
        - name: Slim Docker image
          uses: kitabisa/docker-slim-action@v1
          env:
            DSLIM_HTTP_PROBE: "false"  # Disables HTTP probing during slimming
          with:
            target: ghcr.io/${{ secrets.GIHUB_TOKEN }}/sync_https_server:latest  # Target image to slim
            tag: slim  # Suffix for the slimmed image tag
    
        - name: Push slimmed Docker image
          run: |
            docker push ghcr.io/${{ secrets.GITHUB_TOKEN }}/sync_https_server:slim
