on:
    push: 
        branches:
            - main
            - dev

jobs:
    checking-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
