name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Allow read access to the repository contents
      packages: write # Allow write access to GitHub Packages

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      run: |
        TAG_NAME="${GITHUB_REF_NAME//\//-}"
        docker buildx build \
          --file ./Dockerfile \
          --iidfile /tmp/docker-build-push-BQyhCI/iidfile \
          --platform linux/amd64,linux/arm64 \
          --tag ghcr.io/4goat-4rust/sync_https_server:sha-${GITHUB_SHA} \
          --tag ghcr.io/4goat-4rust/sync_https_server:${TAG_NAME} \
          --push
