name: Deploy and Run
on:
    push: 
        branches:
            - main
            - dev

jobs:
    viewing_repo:  
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4