name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Allow read access to the repository contents
      packages: write # Allow write access to the GitHub Packages

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ vars.REPOSITORY }}/sync_https_server:sha-${{ github.sha }}
          ghcr.io/${{ vars.REPOSITORY }}/sync_https_server:branch-${{ github.ref_name }}
          ghcr.io/${{ vars.REPOSITORY }}/sync_https_server:latest
        push: true

   
